<a href="https://colab.research.google.com/github/KorhanErkan/main.py/blob/master/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK-10A: Please model the AD dataset using the SVM, Decision Tree, and Random Forest algorithms.

Please apply train test split (%75-%25)
Then grid search (hyperparameter tuning)
Then classification report and confusion matrix (on the test dataset)
Then compare the findings from the three algorithms

https://clearpredictions.com/Home/DecisionTree


In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
data = pd.read_excel("AD.xlsx", index_col=0)

In [2]:
y = data["CDRGLOB"]
data.drop(columns = ["CDRGLOB"], axis = 1, inplace = True)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.25, random_state=42)

In [4]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
param_grid = {'C': [0.1, 1, 10, 100],
              'gamma': [1, 0.1, 0.01, 0.001],
              'kernel': ["rbf"]}

grid = GridSearchCV(SVC(), param_grid, refit=True)
grid.fit(X_train, y_train)
grid.best_params_


grid_pred = grid.predict(X_test)
print(confusion_matrix(y_test, grid_pred))
print(classification_report(y_test, grid_pred))

[[133  50   1   0]
 [ 72  36   0   0]
 [ 28  11   0   0]
 [  7   1   0   0]]
              precision    recall  f1-score   support

           0       0.55      0.72      0.63       184
           1       0.37      0.33      0.35       108
           2       0.00      0.00      0.00        39
           3       0.00      0.00      0.00         8

    accuracy                           0.50       339
   macro avg       0.23      0.26      0.24       339
weighted avg       0.42      0.50      0.45       339



In [7]:
from sklearn.tree import DecisionTreeClassifier

In [8]:
params_grid =  {
    'min_samples_leaf': [1, 2, 3],
    'max_depth': [1, 2, 3],
    "min_samples_split":[1,2,3],
    "max_features": ["auto", "sqrt", "log2"]
}

grid = GridSearchCV(DecisionTreeClassifier(), params_grid, refit=True)
grid.fit(X_train, y_train)

grid.best_params_
grid_pred = grid.predict(X_test)
print(confusion_matrix(y_test, grid_pred))
print(classification_report(y_test, grid_pred))

[[142  42   0   0]
 [ 48  53   5   2]
 [ 14  22   0   3]
 [  2   3   0   3]]
              precision    recall  f1-score   support

           0       0.69      0.77      0.73       184
           1       0.44      0.49      0.46       108
           2       0.00      0.00      0.00        39
           3       0.38      0.38      0.38         8

    accuracy                           0.58       339
   macro avg       0.38      0.41      0.39       339
weighted avg       0.52      0.58      0.55       339



In [9]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
param_grid = [{
    'min_samples_split':[2, 3, 4],
    'min_samples_leaf':[2, 3, 4],
    "max_depth": [10, 20, 30],
    'max_features': ['auto'],
}]

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True)
grid.fit(X_train, y_train)
grid.best_params_
grid_pred = grid.predict(X_test)
print(confusion_matrix(y_test, grid_pred))
print(classification_report(y_test, grid_pred))

[[154  30   0   0]
 [ 28  78   2   0]
 [  1  32   6   0]
 [  0   3   4   1]]
              precision    recall  f1-score   support

           0       0.84      0.84      0.84       184
           1       0.55      0.72      0.62       108
           2       0.50      0.15      0.24        39
           3       1.00      0.12      0.22         8

    accuracy                           0.71       339
   macro avg       0.72      0.46      0.48       339
weighted avg       0.71      0.71      0.69       339

